### ISSUE TITLE
Flow for NT Postman

### ISSUE THREAD

**Issue by benmclure** [crafton/NT-Postman#2]
Thank you Crafton for helping out!

The way I envision this working is that whoever is assigned a contact i.e. multipliers or oversees contacts i.e. admins or dispatchers, would be able to click a tick box in profile page for any contact in D.T for "needs an NT posted".

Once the tick box has been engaged, some of the contact's key data, namely:

- Name and surname
- address details
- phone number

would be sent to a separate page e.g. disciple.tools/postman . This page would be specifically for an assigned Postman user. On this page, the postman could see the list of people who have been ticked as needing a NT. 

I have attached a file of what I think the postman view would look like on mobile.
![Disciple Tools Dashboard Ideas](https://user-images.githubusercontent.com/80407688/119226444-2d63ef80-bb1a-11eb-9ab1-22cecedd5b7a.jpg)

The postman would then select the contacts they will be posting to by ticking the required boxes. This would then generate a page (PDF?) which looks like this (if it were an A4 page and the text was smaller :)):
![print list](https://user-images.githubusercontent.com/80407688/119226678-6a7cb180-bb1b-11eb-96a6-8d157cb0c20b.png)

This page could then be printed off as stickers for postal packages.

Once the pages have been printed and the NT's posted, the postman would then click "NT Posted/Archive" to tell D.T to select "Has Bible" in faith steps for the relevant contact. 

Once "NT Posted/Archive" has been clicked the contact's name and data would leave the postman view and be placed in the archive section which could be accessed by clicking the archive button. 

Of course it would be important that dispatchers/admins are also able to view the postman view as required.

Hope this is clear! Thank you brother!

**Comment by crafton** [comment]
Hey Ben, thanks for the detail here. I've moved this to the Project Description section (https://github.com/crafton/NT-Postman/projects) and decomposed it to a set of tasks on a simple Kanban board. Will close this issue.
